### ISSUE TITLE
Automatically add one hour to each event

### ISSUE THREAD

**Issue by enoch85** [owncloud/calendar#216] opened 2016-02-17 22:48 UTC
As it is today you have to write in both the FROM time and the TO time table. 

It would be much better if you just had to write in the FROM time table and that one hour was automatically added. Often meetings aren't longer than 1 hour, and if you want to have a longer appointment, you simply edit the TO time manually.

**Comment by georgehrke** [comment] 2016-02-17 23:13
duplicate of https://github.com/owncloud/calendar-rework/issues/161

**Comment by enoch85** [comment] 2016-03-08 14:10
No, not a duplicate. What I mean is that it should add one hour automatically once you create the event.

**Comment by georgehrke** [comment] 2016-03-08 14:17
Hm, so the scenario is the following:
- You are in the month view and select a day
- By default it's allday, but you want it to be at a specific time
- you remove the allday checkbox and now start and end are both 12am
- instead the end should be 1am

Is this correct?

**Comment by enoch85** [comment] 2016-03-08 14:38
Yes. correct. :)

**Comment by georgehrke** [comment] 2016-03-08 14:38
ok, definitely makes sense :)

**Closed as completed** 2016-04-12 19:07 UTC
Labels: 3 - to review, enhancement-approved, priority, starter issue
