### ISSUE TITLE
Creating a new event and then changing calendar color causes a visual duplication of the new event

### ISSUE THREAD

**Issue by schrauger** [owncloud/calendar#585] opened 2016-06-22 02:50 UTC
Modifying a calendar's color causes a visual duplication (but not actual duplication) of newly created events, if the event was created prior to changing the color. This is only a visual problem, and refreshing the page fixes the visual artifact, but it still is an interface bug.
### Steps to reproduce
1. Create a new event under a calendar.
2. Modify the calendar's color.
3. Now, the new event looks duplicated, one with the old and new color. Old events are updated with no duplication.
4. Refresh the page. The old colored-duplicate is now gone.
### Expected behaviour

The new event should update its color, and there should be no duplicate event with the old color.
### Actual behaviour

The new event gets updated with the new calender color, and yet the previous colored new event stays on the screen as well.
### Server configuration

**Operating system**:
Ubuntu 14.04.4 LTS

**Web server:**
Nginx

**Database:**
MariaDB 10.1

**PHP version:**
PHP 5.5.9-1ubuntu4.17 (cli)
PHP 5.5.9-1ubuntu4.17 (fpm-fcgi)

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Calendar version:** (see ownCloud apps page)
1.2.2

**Updated from an older ownCloud or fresh install:**
Updated

**Signing status (ownCloud 9.0 and above):**
Approved - Is this the signing status?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

Enabled:
  - activity: 2.2.1
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - documents: true
  - encryption: 1.2.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - galleryplus: 15.0.0
  - notes: 2.0.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: true
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - gallery
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

{
    "system": {
        "installed": true,
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "blacklisted_files": [
            ".htaccess"
        ],
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "default_language": "en",
        "defaultapp": "contacts",
        "knowledgebaseenabled": true,
        "appstoreenabled": true,
        "appstore.experimental.enabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtptimeout": 10,
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "30, auto",
        "allow_user_to_change_display_name": true,
        "appcodechecker": "",
        "updatechecker": true,
        "has_internet_connection": true,
        "check_for_working_webdav": false,
        "check_for_working_htaccess": true,
        "log_type": "owncloud",
        "loglevel": "1",
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "America\/New_York",
        "log_query": false,
        "log_authfailip": false,
        "log_rotate_size": 67108864,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 604800,
        "session_keepalive": true,
        "custom_csp_policy": "default-src; script-src *; style-src *; frame-src *; img-src *; font-src *; media-src *",
        "xframe_restriction": true,
        "maintenance": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/***REMOVED SENSITIVE VALUE***\/web-current\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "enable_previews": true,
        "preview_max_scale_factor": 10,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_avatars": true,
        "singleuser": false,
        "datadirectory": "\/var\/www\/***REMOVED SENSITIVE VALUE***\/data",
        "instanceid": "51b8cb0d25d83",
        "version": "9.0.1.3",
        "mail_from_address": "owncloud",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration

**Browser:**
Firefox 47.0

**Operating system:**
Linux Mint 17.3

**CalDAV-clients:**
OwnCloud Web
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment] 2016-08-15 13:52
Can't reproduce on latest master.
As far as I can tell this was fixed with https://github.com/owncloud/calendar/commit/5f0ea35d7b7cefeb9cfc1ebb1b97b01e069a651c

**Closed as completed by georgehrke** 2016-08-15 13:52 UTC
Labels: 1 - to develop, bug, starter issue, unconfirmed
