### ISSUE TITLE
Import Calendar  items - Twice and more

### ISSUE THREAD

**Issue by hitam4450** [owncloud/calendar#487] opened 2016-04-22 09:26 UTC
I try to update an existing calendar by importing a calendar including the updated schedules.
In the Old version ( <1.1) there was a choice, to delete the existing calendar items prior to import. This option does not exist anymore, therefore after importing the calendar. all existing schedules appear twice!

The new calendar app is at least two steps backward in usability !  :frowning: :thumbsdown: :thumbsdown:

Regards, hitam4450

### Steps to reproduce

1.
2.
3.
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
### Server configuration

**Operating system**:

**Web server:**

**Database:**
5.6
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
9.01
**Calendar version:** (see ownCloud apps page)
1.1
**Updated from an older ownCloud or fresh install:**
updated
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**

**Operating system:**

**CalDAV-clients:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by aspdye** [comment] 2016-04-22 13:59
> The new calendar app is at least two steps backward in usability !  :frowning: :thumbsdown: :thumbsdown:

The new calendar app is rewritten completely and uses the newest standards **and** the new DAV-implementation in core which is trendsetting for the whole ownCloud ecosystem 😉 You are right, that not all functions and features are implemented yet ... but these features will come with coming versions. If you want to help, you are welcome to fix some issues here. It's Opensource - Contribute - THX 😉 (Learned quote from @DeepDiver1975 😜)

> I try to update an existing calendar by importing a calendar including the updated schedules.
> In the Old version ( <1.1) there was a choice, to delete the existing calendar items prior to import.

Can you please fill out the issue template. That would help us to reproduce 😅

**Comment by georgehrke** [comment] 2016-04-24 07:26
If I import the very same event twice, I also expect it to appear twice.

cc @jancborchardt

**Comment by jancborchardt** [comment] 2016-04-24 10:32
This basically seems to be a duplicate of https://github.com/owncloud/calendar/issues/326 ?

**Comment by georgehrke** [comment] 2016-04-24 10:43
Hm, not a real dup, but very closely related 

Please excuse my brevity and typos.

**Comment by hitam4450** [comment] 2016-04-24 10:57
Well, if I import twice WITHOUT DELETING Existing schedules, of course they appear twice! ! :laughing:
However, that was not what i was talking about! 

There is no option "**DELETE EXISTING** Schedule" **BEFORE IMPORTING**!
Regards, hitam4450

**Comment by georgehrke** [comment] 2016-05-01 14:26
ok, then it's a dup of #326

**Closed as completed by georgehrke** 2016-05-01 14:26 UTC
Labels: enhancement-proposed
