### ISSUE TITLE
When updating ownCloud from 8.0.4 to 8.1.1: Exception:Symfony\Component\Routingception\RouteNotFoundException,Message:Unable to generate a URL for the named route "calendar_index" as such route does not exist.

### ISSUE THREAD

**Issue by devurandom** [owncloud/calendar#907] opened 2015-08-21 08:53 UTC
When trying up upgrade ownCloud from 8.0.4 to 8.1.1, I get following exception related to calendar:
```
Exception:Symfony\Component\Routingception\RouteNotFoundException,Message:Unable to generate a URL for the named route "calendar_index" as such route does not exist.,Code:0,Trace:
#0 ${HOST_DIR}/htdocs/lib/private/route/router.php(306): Symfony\Component\Routing\Generator\UrlGenerator->generate(calendar_index, Array, false)
#1 ${HOST_DIR}/htdocs/lib/private/urlgenerator.php(65): OC\Route\Router->generate(calendar_index, Array)
#2 ${HOST_DIR}/htdocs/lib/private/helper.php(139): OC\URLGenerator->linkToRoute(calendar_index, Array)
#3 ${HOST_DIR}/htdocs/lib/public/util.php(306): OC_Helper::linkToRoute(calendar_index, Array)
#4 ${HOST_DIR}/htdocs/apps/calendar/appinfo/app.php(30): OCP\Util::linkToRoute(calendar_index)
#5 ${HOST_DIR}/htdocs/lib/private/app.php(139): require_once(/var/www/cloud....)
#6 ${HOST_DIR}/htdocs/lib/private/app.php(120): OC_App::requireAppFile(calendar)
#7 ${HOST_DIR}/htdocs/lib/private/app.php(1173): OC_App::loadApp(calendar, false)
#8 ${HOST_DIR}/htdocs/lib/private/installer.php(214): OC_App::updateApp(calendar)
#9 ${HOST_DIR}/htdocs/lib/private/installer.php(244): OC_Installer::updateApp(Array)
#10 ${HOST_DIR}/htdocs/lib/private/updater.php(480): OC_Installer::updateAppByOCSId(168707)
#11 ${HOST_DIR}/htdocs/lib/private/updater.php(301): OC\Updater->upgradeAppStoreApps(Array)
#12 ${HOST_DIR}/htdocs/lib/private/updater.php(195): OC\Updater->doUpgrade(8.1.1.3, 8.0.4.2)
#13 ${HOST_DIR}/htdocs/core/ajax/update.php(87): OC\Updater->upgrade()
#14 {main},File:${HOST_DIR}/htdocs/3rdparty/symfony/routing/Symfony/Component/Routing/Generator/UrlGenerator.php,Line:134
```

**Comment by RealRancor** [comment] 2015-08-21 10:33
Duplicate of https://github.com/owncloud/core/issues/18224

**Closed** 2015-08-21 11:14 UTC
