### ISSUE TITLE
CalDav link case sensitivity inconsistent over OC versions and calendars

### ISSUE THREAD

**Issue by godfuture** [owncloud/calendar#776] opened 2015-04-19 08:57 UTC
I have updated OC from 8.0.0 to 8.0.2.
After update, Thunderbird Lightening could not find my calendars anymore. Comparing the links used in Thunderbird and those provided on OC calendar app, showed that the user was newly written in capital letter.
Old (does not work with TB): 
/remote.php/caldav/calendars/future/pairshare
```
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>Calendar with name 'pairshare' could not be found</s:message>
```
New (does work with TB): 
/remote.php/caldav/calendars/Future/pairshare
```
<s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
<s:message>User did not have the required privileges ({DAV:}read) for path "calendars/Future/pairshare"</s:message>
```
Somehow the birthday calendar still works in TB with small letter in username:
/remote.php/caldav/calendars/future/contact_birthdays
```
<s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
<s:message>User did not have the required privileges ({DAV:}read) for path "calendars/future/contact_birthdays"</s:message>
```
I suggest one way doing it would make it more consistent, as it should not change in update.

Update: calendar names are not case sensitiv. Name in OC app "PairShare", noted in path "pairshare".

**Comment by georgehrke** [comment] 2015-04-19 08:58
Do you use any user backend?

**Comment by godfuture** [comment] 2015-04-19 08:59
no, only DB.

**Comment by georgehrke** [comment] 2015-04-19 19:16
Are you 100% sure you didn't change something in the config? We didn't change the caldav interface in a while: https://github.com/owncloud/calendar/tree/stable8/lib/sabre

**Comment by georgehrke** [comment] 2015-04-19 19:18
can't reproduce. Works as expected for me

**Comment by RealRancor** [comment] 2015-04-20 19:19
Hi,

not quite sure if this is related but for the "User did not have the required privileges" message there is a longer thread about this available at the core tracker: owncloud/core#14048 where currently a lot of people posting stuff.

**Comment by georgehrke** [comment] 2015-04-20 19:55
@RealRancor thx for the link
closing as dup

**Closed by georgehrke** 2015-04-20 19:55 UTC

**Comment by RealRancor** [comment] 2015-04-21 03:20
@georgehrke
The one in core was closed because some one had written that it is not a core bug. No idea if this is true.

**Comment by johnwoltman** [comment] 2015-04-21 03:49
Someone on the core bug tracker told us to open bugs in the CalDAV/CardDAV projects.  I'm using LDAP as my user back-end, but get the same behavior with my ownCloud admin account.  I upgraded from OC7 to OC8.  Here's my info from the other bug tracker:

Logging in as an LDAP user or as the owncloud administrator account, I cannot view/sync either CardDAV or CalDAV data.  I can use the WebDAV support just fine, but not the Card/CalDAV. 

### Expected behaviour
Should be able to use CardDAV and CalDAV links with iOS and OS X clients or view it with Firefox.

### Actual behaviour
Receive Sabre\DAVACL\Exception\NeedPrivileges exception

### Server configuration
**Operating system**:Centos 7.1 x86_64

**Web server:** Apache 2.4.6

**Database:**  postgresql 9.3.6

**PHP version:** 5.6.7

**ownCloud version:** 8.0.2

**Updated from an older ownCloud or fresh install:** Update from 7

**List of activated apps:**
 - activity          
 - calendar          
 - contacts          
 - files             
 - files_sharing     
 - files_texteditor  
 - files_trashbin    
 - files_versions    
 - files_videoviewer 
 - gallery           
 - news              
 - user_ldap         

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '51d4672e6805c',
  'passwordsalt' => '[redacted]',
  'datadirectory' => '/var/cloud',
  'dbtype' => 'pgsql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => '[redacted]',
  'dbpassword' => '[redacted]',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => 2,
  'log_type' => 'syslog',
  'logfile' => '',
  'maintenance' => false,
  'theme' => '',
  'forcessl' => true,
  'appcodechecker' => false,
  'overwritewebroot' => '/cloud',
  'overwrite.cli.url' => '/cloud',
  'trusted_domains' =>
  array (
    0 => '[redacted]',
  ),
  'secret' => '[redacted]',
);
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Only SSL/TLS, not owncloud file encryption

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)

```
   appid   |             configkey             |                 configvalue
-----------+-----------------------------------+---------------------------------------------
 user_ldap | ldap_agent_password               | [redacted]
 user_ldap | ldap_turn_off_cert_check          |
 user_ldap | bgjUpdateGroupsLastRun            | 1386377150
 user_ldap | ldap_quota_attr                   |
 user_ldap | ldap_backup_host                  |
 user_ldap | ldap_attributes_for_group_search  |
 user_ldap | enabled                           | yes
 user_ldap | ldap_group_filter_mode            | 0
 user_ldap | ldap_cache_ttl                    | 600
 user_ldap | ldap_groupfilter_objectclass      | inetOrgPerson
 user_ldap | ldap_user_filter_mode             | 0
 user_ldap | ldap_group_filter                 | (&(|(objectclass=inetOrgPerson)))
 user_ldap | ldap_backup_port                  | 389
 user_ldap | ldap_configuration_active         | 1
 user_ldap | ldap_login_filter                 | (&(|(objectclass=inetOrgPerson))(uid=%uid))
 user_ldap | ldap_base_groups                  | ou=users,dc=[redacted],dc=com
 user_ldap | ldap_attributes_for_user_search   |
 user_ldap | ldap_tls                          |
 user_ldap | ldap_nocase                       |
 user_ldap | ldap_override_main_server         |
 user_ldap | ldap_quota_def                    |
 user_ldap | ldap_display_name                 | cn
 user_ldap | ldap_userfilter_objectclass       | inetOrgPerson
 user_ldap | home_folder_naming_rule           |
 user_ldap | ldap_expert_username_attr         | cn
 user_ldap | ldap_dn                           | cn=[redacted],dc=[redacted],dc=com
 user_ldap | ldap_port                         | 389
 user_ldap | ldap_expert_uuid_attr             |
 user_ldap | ldap_uuid_attribute               | entryuuid
 user_ldap | types                             | authentication
 user_ldap | ldap_host                         | ldap://[redacted]
 user_ldap | ldap_base                         | dc=[redacted],dc=com
 user_ldap | ldap_email_attr                   | mail
 user_ldap | ldap_nested_groups                | 0
 user_ldap | ldap_paging_size                  | 500
 user_ldap | ldap_base_users                   | ou=users,dc=[redacted],dc=com
 user_ldap | ldap_userfilter_groups            |
 user_ldap | ldap_userlist_filter              | (|(objectclass=inetOrgPerson))
 user_ldap | ldap_groupfilter_groups           |
 user_ldap | ldap_group_display_name           | cn
 user_ldap | ldap_group_member_assoc_attribute | uniqueMember
 user_ldap | ldap_login_filter_mode            | 0
 user_ldap | ldap_loginfilter_email            | 0
 user_ldap | ldap_loginfilter_username         | 1
 user_ldap | ldap_loginfilter_attributes       |
 user_ldap | has_memberof_filter_support       |
 user_ldap | ldap_expert_uuid_user_attr        |
 user_ldap | ldap_expert_uuid_group_attr       |
 user_ldap | last_jpegPhoto_lookup             | 0
 user_ldap | ldap_uuid_user_attribute          | entryuuid
 user_ldap | ldap_uuid_group_attribute         | entryuuid
 user_ldap | ocsid                             | 166061
 user_ldap | ldap_experienced_admin            | 0
 user_ldap | installed_version                 | 0.5.0
 user_ldap | cleanUpJobOffset                  | 0
```

### Client configuration
**Browser:** Firefox 36

**Operating system:** Windows 7 64-bit

### Logs
#### Web server & ownCloud error log
```
Apr 15 01:06:20 [redacted] ownCloud[1768]: {news} Configuration value "simplePieCacheDuration" does not exist. Ignored value.
Apr 15 01:06:20 [redacted] ownCloud[1824]: {news} Configuration value "simplePieCacheDuration" does not exist. Ignored value.
Apr 15 01:13:25 [redacted] ownCloud[6242]: {PHP} Undefined index: REQUEST_URI at /var/www/html/owncloud/apps/calendar/appinfo/app.php#41
Apr 15 01:13:29 [redacted] ownCloud[6245]: {PHP} Undefined index: REQUEST_URI at /var/www/html/owncloud/apps/calendar/appinfo/app.php#41
Apr 15 01:13:34 [redacted] ownCloud[6250]: {PHP} Undefined index: REQUEST_URI at /var/www/html/owncloud/apps/calendar/appinfo/app.php#41
Apr 15 01:20:02 [redacted] ownCloud[6360]: {PHP} Undefined index: REQUEST_URI at /var/www/html/owncloud/apps/calendar/appinfo/app.php#41
Apr 15 01:20:02 [redacted] ownCloud[6360]: {news} Configuration value "simplePieCacheDuration" does not exist. Ignored value.
Apr 15 01:35:41 [redacted] ownCloud[5713]: PHP Fatal error:  Class OC_Connector_Sabre_Auth contains 1 abstract method and must therefore be declared abstract or implement the remaApr 15 01:35:41 [redacted] httpd[5713]: {PHP} Class OC_Connector_Sabre_Auth contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Apr 15 01:36:17 [redacted] httpd[6727]: [Wed Apr 15 01:36:17.474944 2015] [so:warn] [pid 6727] AH01574: module wsgi_module is already loaded, skipping
Apr 15 01:36:17 [redacted] httpd[6727]: AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/httpd/conf.d/com.conf:1
Apr 15 01:40:02 [redacted] ownCloud[7071]: {PHP} Undefined index: REQUEST_URI at /var/www/html/owncloud/apps/calendar/appinfo/app.php#41
Apr 15 01:40:02 [redacted] ownCloud[7071]: {news} Configuration value "simplePieCacheDuration" does not exist. Ignored value.
Apr 15 01:40:53 [redacted] ownCloud[6786]: {carddav} Exception: {"Message":"User did not have the required privileges ({DAV:}read) for path \"addressbooks\/john\/contacts\"","CodeApr 15 01:42:01 [redacted] httpd[7161]: [Wed Apr 15 01:42:01.133809 2015] [so:warn] [pid 7161] AH01574: module wsgi_module is already loaded, skipping

Apr 15 01:42:06 [redacted] ownCloud[7165]: {carddav} Exception: {"Message":"User did not have the required privileges ({DAV:}read) for path \"addressbooks\/john\/contacts\"","CodeApr 15 01:46:34 [redacted] ownCloud[7302]: {PHP} Undefined index: REQUEST_URI at /var/www/html/owncloud/apps/calendar/appinfo/app.php#41
```

#### Browser log
```
None
```

**Comment by johnwoltman** [comment] 2015-04-21 03:51
This has been a problem for me since 8.0.0 was released.  I'd be willing to work with someone on IRC to get it resolved.
