### ISSUE TITLE
Not Compatable with 8.1 RC2 Version

### ISSUE THREAD

**Issue by Pifa1** [owncloud/calendar#826] opened 2015-07-01 21:18 UTC

**Comment by RealRancor** [comment] 2015-07-02 14:55
Make sure you're running the current master as this branch should be compatible with 8.1 according to https://github.com/owncloud/core/issues/17323#issuecomment-117971353

**Comment by georgehrke** [comment] 2015-07-05 19:07
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by enoch85** [comment] 2015-07-07 00:24
@georgehrke Just downloaded 8.1 (updated from 8.0.4) and I experience the same thing. Even the occ command won't install calender due to incompatibility and the update gets stuck in maintenance mode.

Is this just a temporary thing, or will it be released as it is right now together with 8.1? Maybe this is related? https://github.com/owncloud/core/issues/17388

**Comment by PVince81** [comment] 2015-07-07 11:42
I took the calendar app from git master and that one worked on my instance.
Not sure when the official 8.1-compatible app will be published in the app store.

**Comment by georgehrke** [comment] 2015-07-07 11:43
I uploaded them about an hour ago

**Comment by georgehrke** [comment] 2015-07-07 11:44
@Pifa1 @enoch85 please re-test

**Comment by PVince81** [comment] 2015-07-07 11:53
I tested the following:

1. Check out stable8
1. Install calendar from the app store, section "Productivity": worked
1. Check out stable8.1
1. Run the update. It will disable the calendar app and says it's incompatible.
1. Go to apps page, try enabling calendar from the "Not enabled" section: cannot enable, it says it's incompatible.
1. Click "Uninstall" to uninstall it
1. Go to "Productivity" again
1. Enable calendar app: app enables itself
1. App icon is missing in navigation. Also the "Productivity" page says the app is enabled, but the app doesn't appear under the "Enabled" section. It looks like no code was downloaded ?! I can't find the app in any of my "apps" folders.

**Comment by PVince81** [comment] 2015-07-07 11:53
CC @karlitschek

**Comment by karlitschek** [comment] 2015-07-07 11:55
@DeepDiver1975 FYI

**Comment by PVince81** [comment] 2015-07-07 11:55
I tried setting up stable8.1 from scratch. When I enable the calendar app I get "cURL error 60: SSL certificate problem: unable to get local issuer certificate".

**Comment by jospoortvliet** [comment] 2015-07-07 12:01
I was told yesterday by @LukasReschke that CURL issues are due to the platform - broken CURL or something? I had this testing at home, too.

**Comment by LukasReschke** [comment] 2015-07-07 12:20
We might try to disable SNI on apps.oc.com and the API server. Some cURL versions are really buggy.

cc @karlitschek

**Comment by DeepDiver1975** [comment] 2015-07-07 12:21
> Go to apps page, try enabling calendar from the "Not enabled" section: cannot enable or update, it says it's incompatible.

This is most probably related to missmatching ocsids - I had the same with contacts app this morning.

ocs id of calendar as listed in the db has to matchup with the ocsid on the appstore- in addition all ocsids in the downloadable archives have to be identical.

@karlitschek it would be great to have a check on upload of the archives if the ocsid are correct.

**Comment by LukasReschke** [comment] 2015-07-07 12:22
There is for example a bug that when a request to one SNI hosts with different CN's is done always the first one may be used in some buggy PHP versions.

**Comment by PVince81** [comment] 2015-07-07 12:23
I also see two calendar apps: one appears in the "Not enable" section and has the "Update to 0.7.0" button, the one that gives SSL error.
There is another calendar app in the "Productivity" section which only has the button "Enable". So probably an ocs id mismatch ?

**Comment by DeepDiver1975** [comment] 2015-07-07 12:26
this is the old 7.0.0 placeholder - we should remove it

https://apps.owncloud.com/content/show.php/Calendar?content=166043

**Comment by Pifa1** [comment] 2015-07-07 12:27
@georgehrke  . was able to install  Calendar 0.7.0 on ownCloud 8.1 RC2 (testing) . Did not do any extensive testing on calendar itself

**Comment by enoch85** [comment] 2015-07-07 13:00
Not able to test until 3 hours. At work now.

**Comment by enoch85** [comment] 2015-07-07 16:13
I can confirm that the issue with the calendar is gone. At least in this case. Feel free to close.

**Comment by PVince81** [comment] 2015-07-07 16:22
Thanks, closing now.

**Comment by PVince81** [comment] 2015-07-07 16:23
Calendar app update also working on my productive server.

The errors I saw were in my dev env, reported here https://github.com/owncloud/core/issues/17446

**Closed by PVince81** 2015-07-07 16:22 UTC
Labels: needs info
