### ISSUE TITLE
Calendar importing fails when the client is evolution

### ISSUE THREAD

**Issue by jejb** [owncloud/calendar#991] opened 2015-11-25 09:18 UTC
There's a bug in libs/import.php where it always adds a blank VALUE= to the DTEND specification.  Evolution really hates this because it causes a misparse in its ical handling routines which can sometimes cause the imported event not to appear.  Fix this by only copying the VALUE parameter from DTSTART if it actually exists and is non-empty.

[tmp.txt](https://github.com/owncloud/calendar/files/43653/tmp.txt)

**Comment by gvde** [comment] 2015-11-25 10:58
Duplicate of #876

**Closed** 2015-11-25 12:18 UTC
