### ISSUE TITLE
show/hide calendar duplicates event display

### ISSUE THREAD

**Issue by simongareste** [owncloud/calendar#231] opened 2016-02-22 09:28 UTC
### Steps to reproduce
1. create a new calendar
2. create an event in this new calendar
3. click on the left pane on the color box to hide the calendar
4. re-click on the left pane to show the calendar
5. click again to hide
6. refresh the page
7. click to show
8. create an event in the same calendar
9. click to hide
10. click to show
### Expected behaviour

Click to hide should hide all events of the calendar, re-click to show should re-display all events of this calendar, re-click to hide should hide all events. Refreshing the page should not change anything (so it should still be hidden), clicking on show should show all, creating an event creates an event, clicking on hide should hide all, clicking on show should show all.
### Actual behaviour

hiding does not hide, then showing show all events as duplicated (two rows for the same event, identical ), re-hiding hides this second row but still not the first one. Refreshing the page hides all the calendar's events (expected behaviour), showing shows the calendar's events (expected behaviour, no duplicates contrary to before refreshing the page), creating the event adds an event. Hiding hides everything except the newly created event, showing show everything again but with a duplicate on the newly created event.
### Server configuration

**Operating system**: Ubuntu 15.04

**Web server:** Nginx

**Database:** MariaDB 10

**PHP version:** 5.6.5

**ownCloud version:** (see ownCloud admin page) ownCloud 9.0.0 beta 2 

**Calendar version:** (see ownCloud apps page) 0.82

**Updated from an older ownCloud or fresh install:** updated from previous master since 9.0 development

**Signing status (ownCloud 9.0 and above):** ?

```
Integrity checker has been disabled. Integrity cannot be verified.
```

**List of activated apps:**

```
Enabled:
  - calendar: 0.82
  - comments: 0.2
  - dav: 0.1.4
  - federatedfilesharing: 0.1.0
  - files: 1.4.3
  - files_sharing: 0.9.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - federation
  - files_external
  - testing
  - user_ldap
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using encryption:** no (except https)

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox 44

**Operating system:** Mac OS X

**CalDAV-clients:** browser

**Comment by georgehrke** [comment] 2016-02-24 14:50
duplicate of https://github.com/owncloud/calendar-rework/issues/213

**Closed as completed by georgehrke** 2016-02-24 14:50 UTC
