### ISSUE TITLE
events do not show up on Windows Phone 8.1 client since update to Owncloud 8.1

### ISSUE THREAD

**Issue by Garfonso** [owncloud/calendar#853] opened 2015-07-13 17:25 UTC
First: This worked with owncloud 8.0.* -> i.e. some change in owncloud 8.1 must have broken WP8.1 compability

In WP8.1 before the change calendar sync (and also contact sync) worked using carddav and caldav. Contact sync still works. Also calendars themself still show up fine (even if I delete and re-add the account) but calendar events do not show up at all and new events vanish after a short time.

Other caldav clients still work, so it must be something specific. Can I add more information to troubleshoot this issue?

There is also a thread in the forum for this: https://forum.owncloud.org/viewtopic.php?f=31&t=29255&p=91533#p91533

**Comment by georgehrke** [comment] 2015-07-13 17:30
> Can I add more information to troubleshoot this issue?

yes, please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by Bugahans** [comment] 2015-07-13 18:22
With Owncloud 8.1 the sync process on Windows phone is broken.
my device Lumia 930 WP8.1

Sync is enable via the following links:
Calendar: https://MYSITE/owncloud/remote.php/caldav/calendars/USER/pers%C3%B6nlich
Contacts: https://MYSITE/owncloud/remote.php/carddav/addressbooks/USER/kontakte

there are no Errors, sync works

Results:
the calendar is completly empty, wehn I add a new date it is displayed for some seconds, then it disappears. When I check in owncloud the date is saved.
When I add a date to the birthday calendar it stays...


the contacts sync works partly. some contacts are displayed and some not. When I add a new contact it is synced to the owncloud. when I add in owncloud a new contact it is displayed to my wp8 phone. but somehow about 50% of my contacts are missing. There is no common attributes between These contacts.

**Comment by georgehrke** [comment] 2015-07-13 18:23
@Bugahans please use the issue template ...

**Comment by Bugahans** [comment] 2015-07-13 18:33
### Steps to reproduce
1.
2.
3.

### Expected behaviour
sync should work in both directly
Display of Dates
Show all contacts

### Actual behaviour
no Dates displayed
some contacts displayed

### Server configuration
**Operating system**: Synology NAS DS412+

**Web server:** Apache

**Database:**Maria DB (MySQL)

**PHP version:**5.5.26

**ownCloud version:** (see ownCloud admin page) 8.1

**Updated from an older ownCloud or fresh install:** Update from 7 => 8.04 => 8.1

**List of activated apps:**
Activity 2.0.1
Deleted files 0.6.3
First Run Wizard 1.1 
Mail Template Editor 0.1
PDF Viewer 0.7
Pictures 0.6.0
Share Files 0.6.2
Text Editor 0.4
Updater 0.6
Versions 1.0.6
Video Viewer 0.1.3
Calendar 0.7.2
Contacts 0.4.0.0
 

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'XXX',
    1 => 'XXX',    
  ),
  'datadirectory' => '/volume1/web/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'XXX',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'secret' => 'XXX',
  'loglevel' => 4,
);


**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
WP8.1
Lumia 930

**Comment by georgehrke** [comment] 2015-07-13 18:34
@Bugahans please report a separate issue in the contacts repo

**Comment by Garfonso** [comment] 2015-07-13 18:46
### Steps to reproduce
1. Buy a devices with Windows Phone 8.1 (or maybe earlier versions) installed
2. Configure owncloud sync (ab)-using the iCloud-account
3. See that after a sync no events show up in the calendar app, but calendars & contacts are there, also new events from device sync to server.

### Expected behaviour
Events should show up in device calendar app (as it used to work in owncloud 8.0.*)

### Actual behaviour
No events show up in device calendar app, although caldav communication basically works (because calendars show up in calendar app, but no events. Also new events are created on server)

### Server configuration
**Operating system**: 
Windows Phone 8.1 on device / Ubuntu 14.04 (Trusty) 64Bit

**Web server:** 
Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.11 OpenSSL/1.0.1f

**Database:** 
mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:** 
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.1.0 (stable)

**Updated from an older ownCloud or fresh install:**
Updated since ownCloud 6

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - appframework: 0.104
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - mail: 0.1.3
 - user_external: 0.4
Disabled:
 - encryption
 - external
 - mozilla_sync
 - news
 - provisioning_api
 - roundcube
 - search_lucene
 - templateeditor
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
(command spits out error. There are no commands defined in the "config" namespace.)

<?php
$CONFIG = array (
  'instanceid' => '**',
  'passwordsalt' => '**',
  'datadirectory' => '/var/owncloud/data',
  'dbtype' => 'mysql',
  'dbname' => '***',
  'dbuser' => '**',
  'dbpassword' => '**',
  'dbhost' => '***',
  'dbtableprefix' => 'oc_',
  'version' => '8.1.0.8',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => '***',
    1 => '***',
    2 => '****',
  ),
  'loglevel' => '0',
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'tratschtante.de',
  'secret' => '******',
  'overwrite.cli.url' => '/owncloud',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'cron_log' => true,
  'appstoreenabled' => true,
  'has_internet_connection' => true,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:** Windows Phone 8.1 caldav client...

**Operating system:** Windows Phone 8.1

### Logs
#### Web server error log
[Mon Jul 13 19:27:30.639293 2015] [auth_digest:notice] [pid 32657] AH01757: generating secret for digest authentication ...
[Mon Jul 13 19:27:30.783732 2015] [mpm_prefork:notice] [pid 32657] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.11 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Jul 13 19:27:30.783760 2015] [core:notice] [pid 32657] AH00094: Command line: '/usr/sbin/apache2'
tail: inotify resources exhausted
tail: inotify cannot be used, reverting to polling

#### ownCloud log (data/owncloud.log)
{"reqId":"DtKvU8\/7M2tMZX31gizK","remoteAddr":"88.153.98.135","app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>!$_\"","level":0,"time":"2015-07-13T18:40:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/groups\/"}
{"reqId":"xnf8Kd61HaQyGrETL32R","remoteAddr":"88.153.98.135","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-07-13T18:40:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/114\/photo?maxSize=32"}
{"reqId":"xnf8Kd61HaQyGrETL32R","remoteAddr":"88.153.98.135","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-07-13T18:40:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/114\/photo?maxSize=32"}
{"reqId":"ySPgIFVQKBKsrf0IyWvr","remoteAddr":"88.153.98.135","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-07-13T18:40:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/113\/photo?maxSize=32"}
{"reqId":"ySPgIFVQKBKsrf0IyWvr","remoteAddr":"88.153.98.135","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-07-13T18:40:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/113\/photo?maxSize=32"}
{"reqId":"Wmh6MTS1uz0ka5tcY5so","remoteAddr":"88.153.98.135","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-07-13T18:40:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/115\/photo?maxSize=32"}
{"reqId":"Wmh6MTS1uz0ka5tcY5so","remoteAddr":"88.153.98.135","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-07-13T18:40:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/115\/photo?maxSize=32"}
{"reqId":"0h+ToUCPLtj2OKBmTXcR","remoteAddr":"88.153.98.135","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-07-13T18:40:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/112\/photo?maxSize=32"}
{"reqId":"0h+ToUCPLtj2OKBmTXcR","remoteAddr":"88.153.98.135","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-07-13T18:40:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/112\/photo?maxSize=32"}
{"reqId":"JxcXh\/dQO7pSE7thDhgM","remoteAddr":"88.153.98.135","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-07-13T18:40:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/116\/photo?maxSize=32"}
{"reqId":"JxcXh\/dQO7pSE7thDhgM","remoteAddr":"88.153.98.135","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-07-13T18:40:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/116\/photo?maxSize=32"}
{"reqId":"3Np7atomAPLpmj1dEAGq","remoteAddr":"88.153.98.135","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 144\n)\n","level":0,"time":"2015-07-13T18:40:32+00:00","method":"PATCH","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/144"}
{"reqId":"3Np7atomAPLpmj1dEAGq","remoteAddr":"88.153.98.135","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 144\n)\n","level":0,"time":"2015-07-13T18:40:32+00:00","method":"PATCH","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/144"}
{"reqId":"w20791SB+SNBmoDjs2dc","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-07-13T18:45:02+00:00","method":"--","url":"--"}
{"reqId":"w20791SB+SNBmoDjs2dc","remoteAddr":"","app":"files_locking","message":"INFO: Read lock requested for \/var\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-07-13T18:45:02+00:00","method":"--","url":"--"}
{"reqId":"w20791SB+SNBmoDjs2dc","remoteAddr":"","app":"files_locking","message":"PASS: Acquired read lock for \/var\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-07-13T18:45:02+00:00","method":"--","url":"--"}
{"reqId":"w20791SB+SNBmoDjs2dc","remoteAddr":"","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/var\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-07-13T18:45:02+00:00","method":"--","url":"--"}
{"reqId":"w20791SB+SNBmoDjs2dc","remoteAddr":"","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/var\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-07-13T18:45:02+00:00","method":"--","url":"--"}
{"reqId":"w20791SB+SNBmoDjs2dc","remoteAddr":"","app":"search_lucene","message":"background job optimizing index for Achim","level":0,"time":"2015-07-13T18:45:02+00:00","method":"--","url":"--"}
{"reqId":"w20791SB+SNBmoDjs2dc","remoteAddr":"","app":"search_lucene","message":"removed 0 files from index","level":0,"time":"2015-07-13T18:45:02+00:00","method":"--","url":"--"}
{"reqId":"w20791SB+SNBmoDjs2dc","remoteAddr":"","app":"search_lucene","message":"background job optimizing index for Stephanie","level":0,"time":"2015-07-13T18:45:02+00:00","method":"--","url":"--"}
{"reqId":"w20791SB+SNBmoDjs2dc","remoteAddr":"","app":"search_lucene","message":"removed 0 files from index","level":0,"time":"2015-07-13T18:45:02+00:00","method":"--","url":"--"}
{"reqId":"OIEcZTJrnXeWRZU1IzIb","remoteAddr":"88.153.98.135","app":"caldav","message":"Exception: {\"Message\":\"Invalid Mimedir file. Line starting at 17 did not follow iCalendar\\\/vCard conventions\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(189): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readProperty('? cher Stra??e ...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(172): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('? cher Stra??e ...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(137): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('BEGIN:VEVENT')\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(142): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCALENDAR...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(115): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->validateFilterForObject(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(427): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->calendarQuery('5', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(621): Sabre\\\\CalDAV\\\\Calendar->calendarQuery(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(231): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(DOMDocument))\\n#10 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\\\/Achim...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(705): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#13 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#18 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":385}","level":4,"time":"2015-07-13T18:45:18+00:00","method":"REPORT","url":"\/owncloud\/remote.php\/caldav\/calendars\/Achim\/gemeinsam\/"}

#### Browser log
Not accessible

**Comment by Garfonso** [comment] 2015-07-13 18:47
Probably that last message has something to do with the issue. But I can not really decipher it at this point in time.

**Comment by ConiKost** [comment] 2015-07-14 11:43
I can confirm this problem. After updating to ownCloud 8.1, my Windows Phone 8.1 does not show any calender entries or contacts. But none sync errors are shown.

**Comment by stevanb** [comment] 2015-07-14 18:12
Same here.

**Comment by Garfonso** [comment] 2015-07-14 21:12
This still has the need info tag. Can we provide additional information? I can't find a way to get a log or anything from Windows Phone, AFAIK. Maybe somebody knows a way for that, if there is any?

I have full control over my apache2 server and can also offer to test versions cloned from github directly in a test install if that is of any help. I know this probably is not an issue that is easily tackled without a WP8.1 device. :-(

**Comment by stevanb** [comment] 2015-07-15 09:45
I don't have any logging capability seen in Windows phone yet. But if you give me an account on your cloud, you can log my attempts with the phone on your cloud. I only your the hosted Version of the cloud, so my logging is not very verbose.

**Comment by georgehrke** [comment] 2015-07-15 09:46
@jakobsack You have an Windows phone device, right?
Do you have some spare time and some eager to look into this? :)

**Comment by ConiKost** [comment] 2015-07-15 15:00
I am also running ownCloud on my own server. So I can provide at least logs for that and nginx :)

Nginx only shows:
[15/Jul/2015:16:56:57 +0200] "PROPFIND /remote.php/caldav/principals/xxx/ HTTP/1.1" 207 1279 "-" "MSFT-WP/8.10.14219 (gzip)" "-"
[15/Jul/2015:16:56:57 +0200] "PROPFIND /remote.php/carddav/principals/xxx/ HTTP/1.1" 207 1233 "-" "MSFT-WP/8.10.14219 (gzip)" "-"
[15/Jul/2015:16:56:57 +0200] "PROPFIND /remote.php/caldav/calendars/xxx/ HTTP/1.1" 207 3044 "-" "MSFT-WP/8.10.14219 (gzip)" "-"
[15/Jul/2015:16:56:57 +0200] "PROPFIND /remote.php/carddav/addressbooks/xxx/ HTTP/1.1" 207 2105 "-" "MSFT-WP/8.10.14219 (gzip)" "-"

**Comment by jakobsack** [comment] 2015-07-16 15:26
@georgehrke I'll have a look at it tomorrow, ok?

**Comment by georgehrke** [comment] 2015-07-16 15:26
sure, thx a lot :smile:

**Comment by sorglos** [comment] 2015-07-16 21:08
Has anyone enabled the option ```Enable only for specific groups```?

**Comment by kgraefe** [comment] 2015-07-16 21:13
Since I don't know why you're asking that question: I am affected by the bug and I do not have this option enabled.

**Comment by ConiKost** [comment] 2015-07-16 21:16
Same here. I am affected and don't have this option enabled.

**Comment by sorglos** [comment] 2015-07-17 08:38
@kgraefe Disabling the option was the solution for me, but not on Windows Phone. ;-)

**Comment by bolinches** [comment] 2015-07-18 17:59
Same here. I updated to latest 8.1 (8.1.0-16.1) changed URL to what is shown on iCal links on the web interface still does not work. Shows for few seconds, is on owncloud and nothing is shown in the calendar. Contacts are OK

**Comment by arno1979** [comment] 2015-07-18 20:44
@bolinches Exactly what I encounter on my server and phone: same Owncloud version, same links, contacts work fine (both directions), calendars are empty, new entries disappear instantly but are visible on the web interface and also in my calendar app on OS X.
I would really appreciate a solution for this problem. This worked so well and it's one of the few features I really use on my phone.

**Comment by Garfonso** [comment] 2015-07-20 11:59
This still has the "needs info" tag. Can we provide any additional information?

On a sidenote: I updated the calendar app to 0.7.2, which did not help the issue at all, sadly. 

Another sidenote: It seems the log I posted above is not related to Windows Phone. In fact Windows Phone does not produce any log entries, it seems. ((The errors were caused by some slightly corrupted events. Those did not bother earlier versions of sabre dav, but suddenly the are now spitting out errors over the place... So I took the time and manually repaired them. But Windows Phone still won't sync at all.))

**Comment by jakobsack** [comment] 2015-07-20 20:35
Hi guys, did someone notice that shared calendars are not affected?
@georgehrke I just updated my owncloud server and most in my family have Windows Phone, so I'm certainly trying to fix this.

**Comment by bolinches** [comment] 2015-07-20 20:39
@jakobsack Thanks! Nothing like relatives incentive ;)
I have a WP as personal where I cannot see neither my private calendar nor the shared. On the Android, web MacOS, and lighting all seems in order.

**Comment by arno1979** [comment] 2015-07-20 21:02
@jakobsack I have one shared and one private calendar and both are affected, makes no difference in my case.

**Comment by Garfonso** [comment] 2015-07-20 21:06
For me the same. Or what kind of "shared" are you talking about? IIRC all the "shared" calendars I have in my owncloud account are shared with a group.

**Comment by ConiKost** [comment] 2015-07-20 21:41
For me also. I don't have any shared calendar.
But me bothers, why you can sync contacts?
I can clearly reproduce, switching back to 8.0.4, contacts+calendar works again and switch back to 8.1, both fails, not only calendar, as here described?

**Comment by Garfonso** [comment] 2015-07-20 21:45
For contacts I see this:
On a phone that previously synced contacts, the contacts stay (but are probably not updated)
On a phone where I did setup a new account with owncloud 8.1 server, only one of my addressbooks is synced.

**Comment by ConiKost** [comment] 2015-07-20 21:47
That's odd. My contacts all disappeared immediately, when syncing with 8.1, even when previously synced with 8.0.4. Did you renamed you carddav-link?

**Comment by jakobsack** [comment] 2015-07-20 22:02
I think I fixed this issue by manually applying the patch from fruux/sabre-dav@ca91f5a9603e53cd4edef2749996ae600cf742a9 to 3rdparty/ to 3rdparty/sabre/dav/lib/CalDAV/Plugin.php in the ownCloud directory.

Can anyone confirm this workaround? You might have to create an event in order to refresh the calendar, it did not work with a "sync account" for me

**Comment by jakobsack** [comment] 2015-07-20 22:05
@ConiKost @Garfonso please do not discuss problems with the contacts app in this issue! It's better to create a new issue in the contacts repository.

**Comment by ConiKost** [comment] 2015-07-20 22:11
Workaround is working for me. Calendar is now syncing with 8.1.

**Comment by bolinches** [comment] 2015-07-21 06:37
I might be doing something wrong. My Sabre is on 2.1.3 (2015-02-25) and those files are referring to 3.1.X I can see and changed the 3rdparty/sabre/dav/lib/CalDAV/Plugin.php then sync stop working all together. I cannot find  tests/Sabre/CalDAV/PluginTest.php on my 2.1.3

**Comment by ConiKost** [comment] 2015-07-21 06:59
I've only changed owncloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php. You don't have to modify PluginTest.php.

**Comment by Garfonso** [comment] 2015-07-21 07:20
Works for me, too. Creating events really is necessary, in order to make WP8 check the calendars again.

I posted a how to for the patch in the forum thread (linked in the first post of this thread). I think a the forum is more appropriate for this kind of hands on help. :)

**Comment by arno1979** [comment] 2015-07-21 07:41
Works with my installation as well. The row numbers from the patch were not correct for my version of Plugin.php but a little bit further down.
@Garfonso Thanks for the hint with creating a new event to force re-syncing, only that worked.

**Comment by Garfonso** [comment] 2015-07-21 07:45
@arno1979 credit for this should go to @jakobsack, he mentioned already. 

From a caldav point of view,  this makes sense, of course. Because WP8 could receive the information about the calendars (just not about the events in the calendars) and stores the ctag for each of them. So unless something in the calendar changes and therefore the ctag changes, WP8 will think that the local copy is in sync and the calendar can be skipped.

**Comment by arno1979** [comment] 2015-07-21 07:54
@Garfonso My mistake! All the credit goes to @jakobsack , thanks for helping us out!

**Comment by kgraefe** [comment] 2015-07-21 08:37
@Garfonso Thank for the details. That could explain why it didn't work for me: I created a new event on the WP8. While the new event did not vanish the other events were still not synced to the phone. I will try again this evening. (The WP8 is my girlfriends phone...)

**Comment by bolinches** [comment] 2015-07-21 10:18
Fixes the issue for me as well. fruux/sabre-dav@ca91f5a + create event as has been already mentioned above. Thanks a lot guys.

**Comment by jakobsack** [comment] 2015-07-21 10:51
FYI: I created a patch upstream at fruux/sabre-dav#692. If they accept this patch and release a new version soon everything should be fine with the next ownCloud 8.1 release.

If this does not work out we could patch sabre in our 3rdparty repository (see owncloud/3rdparty#186). This solution is far from being elegant but it would work for the moment.

**Comment by georgehrke** [comment] 2015-07-23 19:34
https://github.com/owncloud/core/pull/17802

will be fixed with the next ownCloud update (not calendar update!)

**Closed by georgehrke** 2015-07-23 19:34 UTC
Labels: bug, CalDAV

**Comment by Garfonso** [comment] 2015-11-28 22:29
This issue re-surfaced for me on Windows Phone 10, today.
The reason is a different User Agent: "REPORT /owncloud/remote.php/caldav/calendars/Achim/defaultcalendar/ HTTP/1.1" 400 1135 "-" "MSFT-WIN-4/10.0.10586 (gzip)"

So the patch needs to be adjusted. Should I open a new issue for that?

**Comment by dklinger** [comment] 2015-12-06 13:22
Yeah, have the problem, too. Syncing does not show anything on Windows 10 and Windows 10 Mobile.
