### ISSUE TITLE
1.2.1 calendar doesn't show up after upgrade

### ISSUE THREAD

**Issue by Luticus** [owncloud/calendar#538] opened 2016-05-18 12:41 UTC
### Actual behaviour

Tell us what happens instead
The calendar app shows no calendars, and almost no interface.  everything is basically broken.
### Server configuration

**Operating system**:
debian 8
**Web server:**
apache
**Database:**
mysql
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
9.0.2
**Calendar version:** (see ownCloud apps page)
1.2.1
**Updated from an older ownCloud or fresh install:**
updated

Is there an achieve of old version snapshots.  it would be nice to have if not so when an update breaks everything people can easily roll back.  Luckily I always back up apps before I upgrade them but it would still be nice just in case.

**Comment by georgehrke** [comment] 2016-05-18 12:44
Please use the entire issue template ...

**Comment by aspdye** [comment] 2016-05-18 12:59
You can fetch old releases here: https://github.com/owncloud/calendar/releases

Have you updated via AppStore or have you downloaded it from GitHub :grin:

**Comment by Luticus** [comment] 2016-05-18 13:03
I tested this on chrome, with mac os initially.  Haven't had a chance to test it on anything else.

I am unable to get all of the information at the moment as I'm not physically in front of the server, but I'll attempt to give you what extra stuff I can.  

For reproduction all I did was upgrade the app, click calendar, and observe that everything was broken, absent, not functional.  As in the screen was mostly blank where the calendars should be, and there were no calendars on the left column to select.  Rolling back to 1.1 instantly fixes the issue. 

Code signing is disabled on my server, so it doesn't apply to me.  This is due to the extra security and external sites apps which require me to add and edit files that trip the signing feature.  The calendar app is in perfect pristine, state though, and so are all the files in owncloud with the lone exceptions of the icon files for external sites and the extra line in remote.php for extra security.  ("require_once 'apps/extrasecurity/lib/intercept.php';" )

I am using the standard user backend, not ldap or anything else.

I also tested with my oc theme disabled just in case with no difference in results.  

There are people who use caldav with android, kontact, ios, mac osx el capitan, and pretty much anything else out there.

If you need me to then when I'm in a better spot (not at work) I'll grab the template and fill it to completion.  I just thought I should report the bug early incase it impacted others too.

**Comment by Luticus** [comment] 2016-05-18 13:04
Thanks, aspdye.  I'll save that link :)

**Comment by georgehrke** [comment] 2016-05-18 13:18
Works just fine for me with Chromium 52 on OS X
more infos would be appreciated 😉

**Comment by hitam4450** [comment] 2016-05-18 13:39
Upgrade Version 1.2.1 from Version 1.2 works fine on OC 9.0.2 and access by 
FF 46 on UBUNTU 12.04 & 14.04
Regards, hitam4450

**Comment by Luticus** [comment] 2016-05-18 13:58
Is there a requirement to come from v1.2?  I was upgrading from 1.1.

**Comment by georgehrke** [comment] 2016-05-18 13:58
No, there is no requirement.

**Comment by Luticus** [comment] 2016-05-18 14:00
Ok, I attempted the upgrade again through the oc interface (same as before) and it works now.  Maybe it was just a bad update attempt for some reason.  Thank you for the troubleshooting!  :)

**Comment by georgehrke** [comment] 2016-05-18 14:04
Hm, maybe just some caching issue 😕
Anyway, issue solved (itself), will close it.

**Comment by Luticus** [comment] 2016-05-18 14:27
Turns out it's still an issue.  when i rolled back the calendar app, it had the wrong permissions so the update button in the interface could not update properly (it was stuck at 1.1).  Once I fixed the permissions and rolled it forward it broke again.  

I tried removing the app entirely, and then installing 1.2.1 fresh, still broke.

Here's a list of apps i have enabled and their versions, if it helps.

announcement center 1.2
collaborative tags 0.2
comments 0.2
deleted files 0.8.0
external sites 1.2
external storage support 0.5.2
gallery 14.5.0
mail template editor 0.1
notifications 0.2.3
pdf viewer 0.8.1
provisioning api 0.4.1
share files 0.9.1
text editor 2.1
update notification 0.1.0
versions 1.2.0
bookmarks 0.7
calendar 1.2.1
contacts 1.2.0.0
documents 0.12.0
javascript xmpp chat 3.0.0
news 8.7.5
tasks 0.9.0
epub and comics online reader 7.0.5
extra security 0.2.0
file locking
own note 1.07
passwords 18.0
pint 1.0.1
rainloop 4.15
reader (ebook reader) 0.7.1
videos sublime 0.9.8

**Comment by georgehrke** [comment] 2016-05-18 14:31
Wow, that's quite a big list.
I'm wondering why you were even able to enable "extra security". According to apps.ownCloud.com it's maximum version is ownCloud 8

**Comment by Luticus** [comment] 2016-05-18 14:36
I forced it by tweaking the file that checks that.  I liked the feature of being able to join users to a disabled group rather than out right deleting their accounts.  Kinda hoping that features makes it into oc at some point so i can get rid of the app, seeing as development on it seems to have stopped.  It hasn't given me any issues so far.  

And yea, my app list is big because I want owncloud to "be all it can be".  ;)

**Comment by Luticus** [comment] 2016-05-18 14:44
Actually now that i look at it, i don't think that was one that needed anything special to enable.

**Comment by Luticus** [comment] 2016-05-18 17:06
ok so further testing on 1.2.1 shows that the calendar works and draws on firefox mobile on android.  so whatever the issue is it's with chrome _i think_.  Safari doesn't seem to like owncloud, in general, so i can't test with that.

I have tried clearing the cache, opening and closing the browser, etc.  nothing works.  Also i noticed that in FF mobile i can no longer create events.  When i tap an empty date nothing happens, but it used to give me the create an even dialogue.  Might try install FF on my mac and seeing what i get there.

FYI:  This is on chrome 48.0.2564.116.  Might see if there's a chrome update available and test after that too.

**Comment by Luticus** [comment] 2016-05-18 17:15
Ok, Calendar 1.2.1 DOES work in firefox on mac osx.  I did an update on chrome (though it looks like there wasn't a version change), but chrome still does not show the calendar.

**Comment by vetienne** [comment] 2016-05-19 06:15
Same problem here.
After upgrade works in firefox, broken in chrome.  
In chrome i have the same error as in #535 so maybe that's only one issue

**Comment by vetienne** [comment] 2016-05-19 06:43
quick and dirty workaround 

replacing line 1586 of calendar/app.js by

```
   if(Array.isArray(hue)) {
            //[hue, saturation, lightness] = hue;
            var h = hue.hue;
            var s=hue.saturation;
            var l=hue.lightness;

            hue = h;
            saturation = s;
            lightness = l;
    }
```

and line 1644 by
/*
- Convert rgb array to hex string
  */
  var rgbToHex = function(r, g, b) {
      'use strict';
      if(Array.isArray(r)) {
              var red, green, blue;
  
  ```
          red = r.r;
          green = r.g;
          blue = r.b;
          r = red;
          g = green;
          b = blue;
  ```
  
  //              [r, g, b] = r;
      }
      return '#' + parseInt(r, 10).toString(16) + parseInt(g, 10).toStri$
  };

make it work again in chrome 

I think taht's the intended behaviour  but i'm not fluent in javascript so please advise on a better implementation

**Comment by georgehrke** [comment] 2016-05-19 09:41
@skjnldsv What you mind taking a look? ^

**Comment by skjnldsv** [comment] 2016-05-19 16:22
Wut, since when does javascript not allow a direct array assignment?
It work fine on my chrome, this is strange.

**Comment by georgehrke** [comment] 2016-05-19 16:28
@vetienne What OS do you use?

@skjnldsv I'm not even sure if Safari supports that one, it's not a big friend of ES6.

**Comment by georgehrke** [comment] 2016-05-19 16:30
(seems to work fine in latest Safari (the stable one))

**Comment by vetienne** [comment] 2016-05-19 17:02
At least forme : Works in chrome Version 50.0.2661.94 built on Debian stretch/sid, running on Debian stretch/sid (64-bit)
but doesn,"t with an older version ( 47.0.2526.80-1 on debian also )

**Comment by skjnldsv** [comment] 2016-05-19 17:07
Ok, we need to change the assignation! :)

**Comment by vetienne** [comment] 2016-05-19 17:08
Having done somme googling it seems that array assignement has been added on version 49 of chrome so not so old

**Comment by georgehrke** [comment] 2016-05-19 19:34
Ok, so that's how we'll move forward:
- I'll prepare a fix and send a PR
- get 1.2.2 out asap

**Comment by georgehrke** [comment] 2016-05-19 19:54
PR is here: https://github.com/owncloud/calendar/pull/547

**Comment by vetienne** [comment] 2016-05-19 20:15
Sorry for my false solution,  as an excuse i'm just a C programmer so array destructuring is something like alien code for me. At least it gives ypu some clue for gibing a correct solution

**Comment by skjnldsv** [comment] 2016-05-20 03:05
No need to be sorry! :)
Thanks for finding this bug, I didn't know ES6 array was this recent in browsers!

**Closed as completed** 2016-05-20 14:17 UTC
Labels: 1 - to develop, bug, priority

**Comment by georgehrke** [comment] 2016-05-20 14:25
I just released 1.2.2, should be resolved now :)

**Comment by Luticus** [comment] 2016-05-20 14:54
Awesome, thanks!  Trying it out now.

**Comment by Luticus** [comment] 2016-05-20 14:58
Yep. Issue seems fixed to me.  Thanks for all the help!

**Comment by georgehrke** [comment] 2016-05-20 14:58
I'm glad it's fixed :)
