### ISSUE TITLE
Show Full Name instead of username for shared calendars 

### ISSUE THREAD

**Issue by aspdye** [owncloud/calendar#416] opened 2016-04-04 18:59 UTC

**Comment by georgehrke** [comment] 2016-04-05 07:40
- [x] check if there is a way to get the display name for any user in JS
  - [ ] if not ask core to add display name to dav responses

**Comment by wiswedel** [comment] 2016-04-07 18:35
Not really a bug, more a CR, isn't it?

**Comment by georgehrke** [comment] 2016-04-07 19:03
@wiswedel: Well, the LDAP backend has random strings as user Ids, that's why we should use the display name instead :wink:

**Comment by wiswedel** [comment] 2016-04-07 19:18
Ah ok, in that case I understand.

**Comment by georgehrke** [comment] 2016-04-09 19:44
https://github.com/owncloud/core/issues/23877#issuecomment-207833512

**Comment by georgehrke** [comment] 2016-04-11 13:58
duplicate of https://github.com/owncloud/calendar/issues/379

**Closed as completed by georgehrke** 2016-04-11 13:58 UTC
Labels: bug, needs info

**Comment by ksteinb** [comment] 2016-06-13 11:27
Hi Georg,

where do I find the patch for this problem, I have  the version  1.2.2 installed and I have the problem. Also I do not find the patch anywhere on github?

**Comment by georgehrke** [comment] 2016-06-13 11:28
This is a duplicate of #379 which is still open. It wasn't fixed yet.
Contributions welcome :wink:

**Comment by ksteinb** [comment] 2016-06-13 14:57
Hi Georg,

> This is a duplicate of #379
> https://github.com/owncloud/calendar/issues/379 which is still open.
> It wasn't fixed yet.

I did try to output shareWithDisplayName instead of shareWith in the
app.js file but to no help, its probably set to owncloud_name.

It looks like there are more changes needed, the apps probably needs to
use OCP\IUsermanager

Sincerly,
Klaus
