### ISSUE TITLE
Users are unable to create / modify events on the shared calendar

### ISSUE THREAD

**Issue by ittrend4710** [owncloud/calendar#836] opened 2017-12-18 09:33 UTC
Issue:
- User A creates a calendar and shares it with User B
- User B can see the shared calender, but cann't create or modify events
- Additionally some of the shared calenders aren't showed in "calender" section, but in "subscription"

![2017-12-18 10_22_17-spiceworks - tickets ri offen](https://user-images.githubusercontent.com/34334575/34098803-dff6a7ae-e3dd-11e7-8fad-ed3b5c3cdb93.png)

----------------

Initial Idea was an OC Upgrade vom 8.1 -> 10 AND Migration to 64bit System

Starting at:
- openSUSE 13.1 i586 (32bit)
- ownCloud 8.1.9
- Calendar 0.7.4

----------------

Did the following:
openSuSE 13.1 to 13.2 (32bit) regarding OC 10 dependencies
System is on
- Apache2: 2.4.10-31.1
- MySQL: 5.6.34-2.23.1
- PHP: 5.6.1-89.1

----------------

- Update ownCloud 8.1.x -> 8.2.x
- Update ownCloud 8.2.x -> 9.0.x
ran into this issue: #800
solved it like this:
go to lib/private/integritycheck/checker.php and just returning false in function isCodeCheckEnforced

----------------

ownCloud Update 9.0 -> 9.1 ... using:
sudo -u wwwrun php occ dav:migrate-calenders
sudo -u wwwrun php occ dav:migrate-addressbooks
ran into the same error -> see "calender issue" above ... fixed it the same way

next error - if I try to activate the calender app - "App Folder already exists", so I did:
rename Foldername to Foldername.old (in app Subdirectory)
Installed the App from Webgui again

----------------

ownCloud Update 9.1 -> 10.x ... next error during "sudo -u wwwrun php occ upgrade"
Repair warning: Please install or update the following apps manually or disable them with ... did it:
occ app:disable activity
occ app:disable calendar
occ app:disable filespdfviewer_
occ app:disable filestexteditor_
occ app:disable gallery

updated all apps using webgui

----------------

next step should be the migration from 32bit to 64bit system...
...but at first I've to fix the calender issue!

Calender worked till "9.1 -> 10.x"

----------------

initially this issue was diskussed at https://github.com/owncloud/calendar/issues/830#issuecomment-352350491 which was opened by SimoneCampinoti ... for clearing up the situation (Simone was talking about "non-proprietary users") DeepDiver1975 decided to separate it and forced me to open a new case...

Best,
Mike

**Comment by ittrend4710** [comment] 2017-12-18 09:36
so, let's proceed ;-)

**Comment by DeepDiver1975** [comment] 2017-12-18 09:38
If a calendar is shown as subscription it has been share read-only (which is the default).

Once you share it in write mode it will show as calendar and you can edit items.

Let me know if this helps.

**Comment by ittrend4710** [comment] 2017-12-18 10:29
unfortunately not, behavior is like this:
- Login UserA ... go to calender ... check the share settings
- UserB (aka BUERO) is registered twice ... the initial one with "can edit" and a new entry with "read only"
see screenshot:
![screen](https://user-images.githubusercontent.com/34334575/34101432-0aa5754a-e3e6-11e7-8aeb-c6ebe544f55d.png)

i tried the following:
- enabled "can edit" on the second / double / new entry
- deleted both entries and created a new one with "can edit"

if i logoff and relogon with UserA ... the settings weren't saved ... the're appearing like on the screenshot again...

I can remember that I found a similar threat a few days again, but I cann't find it again...

**Comment by DeepDiver1975** [comment] 2017-12-18 10:47
hmmm ... why are there two entries for BUERO?

**Comment by ittrend4710** [comment] 2017-12-18 11:16
this is what I'm asking for ... and changes won't be saved

it happens since the last upgrade step 9.1 -> 10.x

**Comment by ittrend4710** [comment] 2017-12-18 11:17
database issues? I can remember that I found a similar threat ... there where some tables / rows missing, i think...

**Comment by DeepDiver1975** [comment] 2017-12-18 11:37
> database issues?

very probably - please have a look into the table oc_calendars and find out about the id of the calendar which causes trouble. Next please have a look at the table oc_dav_shares - the columns resourceid holds the calendar id. 

I expect duplicates there ....

**Comment by DeepDiver1975** [comment] 2017-12-18 11:38
And having a look into the log file in data/owncloud.log might help as well - not saved changes should write errors inside

**Comment by ittrend4710** [comment] 2017-12-18 12:10
oc_dav_shares looks like this:
![dav1](https://user-images.githubusercontent.com/34334575/34104931-c3ee0272-e3f2-11e7-9da2-60cf1dc1d559.png)

----------------------

logged in as UserA: I tried to delete "buero/BUERO" Entries from Calender sharing using the web-gui ... and finally I logged of as User A ... seems to work, no results in oc_dav_shares as well ... see:
![dav2](https://user-images.githubusercontent.com/34334575/34105035-2d06ba74-e3f3-11e7-8762-a804e4fa3294.png)

no showy entries in the owncloud.log, except this one ... see:
![log1](https://user-images.githubusercontent.com/34334575/34105111-6c40ebec-e3f3-11e7-96a1-4ab48b2dd85d.png)

----------------------

logged in as User A again and tried to share the calender with User B (aka buero/BUERO) using the webgui with "edit" option...

oc_dav_shares looks like this: **got 2 Entries again**
![dav3](https://user-images.githubusercontent.com/34334575/34105338-28a6022c-e3f4-11e7-852b-72427811881a.png)

and owncloud.log shows: **"Sharing backend for principals not found"**
see attached log: 
[log2.txt](https://github.com/owncloud/calendar/files/1567800/log2.txt)

**Comment by DeepDiver1975** [comment] 2017-12-18 12:14
Strange - why is it uppercase and lowercase? Can I see the users page? Are there two users?

**Comment by ittrend4710** [comment] 2017-12-18 12:22
...web-gui, see: (only one User called "buero" ... lowercase)
![user](https://user-images.githubusercontent.com/34334575/34105918-7fbde820-e3f6-11e7-9baa-3f62f183b96f.png)

**Comment by DeepDiver1975** [comment] 2017-12-18 13:42
crazy ... I'll try to reproduce this behavior .... what browser are you using?

**Comment by ittrend4710** [comment] 2017-12-18 13:48
Version 63.0.3239.84 (official build) (64-Bit) ... but as I wrote ... my users contaced me after the upgrade to version 10 and told me that the calender app is doing strange things ... so I don't believe that's browser related

do you want to check it on my system using teamviewer ... i can create a meeting ... and you can safe time trying to reproduce it...

**Comment by ittrend4710** [comment] 2017-12-19 14:44
hello there ... any ideas about that?
what about remote session tomorrow, together?
best,
mike

**Comment by DeepDiver1975** [comment] 2017-12-20 12:28
A remote session will no help much - I need to debug the server code while the requests are executed.

Please drop a screenshot of the table oc_accounts for the users which are involved in this scenario (usera and buero) - THX

**Comment by ittrend4710** [comment] 2017-12-20 15:20
here you are
![bgf](https://user-images.githubusercontent.com/34334575/34214102-bb42f53c-e5a1-11e7-85c8-e0bdf8d99030.png)
![buero](https://user-images.githubusercontent.com/34334575/34214103-bb5be326-e5a1-11e7-9878-6fd3c75a1cca.png)

**Comment by DeepDiver1975** [comment] 2017-12-20 15:28
hmmm .... is this bloody code by accident using the displayname?

Retesting .......

**Comment by ittrend4710** [comment] 2017-12-20 15:30
curious...

**Comment by DeepDiver1975** [comment] 2017-12-20 18:47
I have it reproduced! Finally!

![bildschirmfoto von 2017-12-20 19-46-43](https://user-images.githubusercontent.com/1005065/34223151-8eec32f6-e5be-11e7-9b7f-c595e7ec0a38.png)

**Comment by DeepDiver1975** [comment] 2017-12-20 18:51
@Julian1998 this requires js - fun for you! 😉

**Comment by ittrend4710** [comment] 2017-12-21 07:30
sounds good - please explain

**Comment by DeepDiver1975** [comment] 2017-12-21 09:03
> sounds good - please explain

On the initial share request the user id is used. On the second request the displayname is used which is stupid ....

We need to fix the calendar front end but also the backend and verify if the sent principal is a valid one.

**Comment by ittrend4710** [comment] 2017-12-21 09:45
thanks für update - please keep me up to date

**Comment by DeepDiver1975** [comment] 2017-12-21 10:09
@ittrend4710 the fix is in https://github.com/owncloud/calendar/pull/839

**Comment by ittrend4710** [comment] 2017-12-21 12:40
hello there!

@DeepDiver1975 ... already tested the fix like this:

- changed /apps/calendar to the new one
- Login as UserA and deleted the actual (wrong/double) sharing entries
- Logoff & Relogin as User A and created a share entry für User Buero with write access
- Login as User Buero and tested it ... User is now able to edit etc.

so the new code seems to work correctly -> GOOD WORK!!!

...but, the actual entries inside the database aren't corrected yet, so this would be a huge workload to manually correct all the sharings.

Any Idea about SQL-Statement to do this directly on database? (change the defective ones)

Best,
Mike

**Comment by ittrend4710** [comment] 2018-01-02 13:25
happy new year :-)

...any news about that?

best,
mike

**Comment by DeepDiver1975** [comment] 2018-01-02 14:27
I am offline until january 8th.  Will respond then.

**Comment by DeepDiver1975** [comment] 2018-01-08 08:39
I will work on database cleanup these days - will require a patch to core.

**Comment by ittrend4710** [comment] 2018-01-08 08:42
thanks a lot ... if you wanna me to do testing, please inform
best,
mike

**Comment by ittrend4710** [comment] 2018-01-16 10:11
Dear ... any news about that?
Best,
Mike

**Comment by DeepDiver1975** [comment] 2018-01-16 11:15
we are finalizing 10.0.5  - a fix for this will come with 10.0.6

**Comment by ittrend4710** [comment] 2018-01-16 11:31
Great – thanks for replay  
Two questions: 
1) is there a release date for 10.0.6 ??? 
2) is there a manual (sql) way to correct the database entries? I’m asking because if we cann’t do it like this, we’ll have to manually change alle the calender shares in the gui … and this’ll be a hard work Best,Mike

**Comment by DeepDiver1975** [comment] 2018-01-16 11:40
I edited the message above - had css inside .... bloody html email ...

**Comment by DeepDiver1975** [comment] 2018-01-16 11:43
> 1) is there a release date for 10.0.6 ???

not yet



> 2) is there a manual (sql) way to correct the database entries?

All I can think of at the moment is to delete invalid entries. So basically all those where a wrong principal url was set. I cannot merge the entries because the display name is not gauranteed to be unique and this could result in calendars being share with people which are not allowed to get access.

I think it is necessary to manually fix the sharing settings in the ui. Cleanup will come later

**Comment by ittrend4710** [comment] 2018-01-16 16:17
Ok, please keep me up to date. Best,Mike  From: Thomas Müller [mailto:notifications@github.com] Sent: Tuesday, January 16, 2018 12:43 PMTo: owncloud/calendarCc: Michael Wagner | it-TREND; MentionSubject: Re: [owncloud/calendar] Users are unable to create / modify events on the shared calendar (#836) is there a release date for 10.0.6 ???not yetis there a manual (sql) way to correct the database entries?All I can think of at the moment is to delete invalid entries. So basically all those where a wrong principal url was set. I cannot merge the entries because the display name is not gauranteed to be unique and this could result in calendars being share with people which are not allowed to get access.I think it is necessary to manually fix the sharing settings in the ui. Cleanup will come later—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.it-TREND, Information Technologies Industriestrasse 28 | 4710 Grieskirchen, Austria Telefon/Phone: +43-7248-61778 | eMail: office@it-TREND.at | Web: www.it-TREND.at
 
Ihre Meinung ist uns wichtig! Wie zufrieden sind Sie mit uns und unserer Leistung? Bewerten Sie uns hier: https://de.surveymonkey.com/r/6NQVCHP
Verzichtserklaerung: Der Inhalt dieses eMails kann vertrauliche Informationen enthalten, zu deren Geheimhaltung der Empfaenger verpflichtet ist. Die Informationen dieses eMails sind ausschließlich für den Adressaten bestimmt.
Disclaimer: The contents of this eMail may contain confidential information, which the recipient is obliged to treat as. The information in this eMail is made available exclusively for use by the addressee.

**Comment by ITTRI4710** [comment] 2018-02-06 14:36
We can no longer edit the permission what the user is allowed to do.
In the picture you can see that you can adjust the authorization by adding, changing and deleting. That was before the update was it forgotten?

Best,
Roland
[
![2018-02-06 14_35_17-microsoft edge](https://user-images.githubusercontent.com/34244878/35864936-7255d614-0b53-11e8-9b63-e923992da043.png)
](url)

**Comment by DeepDiver1975** [comment] 2018-02-07 09:34
@ITTRI4710 I don't get your point - do you experience the same trouble as described above? Then you have to wait for the new release of the calendar app and a new server version 10.0.8 (10.0.6 and 10.0.7 are hotfix releases due to regressions we detected)

**Comment by ITTRI4710** [comment] 2018-02-07 12:39
We have the fix installed and it works. We have changed the permission manually. Only creating, modifying and deleting dropdown permission is missing. See Image. 
![2018-02-07 12_58_14-microsoft edge](https://user-images.githubusercontent.com/34244878/35916909-529b5e3e-0c0c-11e8-81a5-cb08bea87c77.png)


Best,
Roland

**Comment by ITTRI4710** [comment] 2018-02-12 09:30
... any news about that?
Best,
Roland

**Comment by DeepDiver1975** [comment] 2018-02-12 10:21
> We have the fix installed and it works. We have changed the permission manually. Only creating, modifying and deleting dropdown permission is missing. See Image.

so please open a new issue and we continue in there - THX

**Comment by DeepDiver1975** [comment] 2018-02-12 17:03
calendar 1.5.5 just has been released

**Comment by ittrend4710** [comment] 2018-02-21 13:32
Hello there,
thanks a lot ... as far as i know calendar isn't an optional app anymore ... so I've to Upgrade to 10.0.6 Release, right?
Best,
Mike

**Comment by DeepDiver1975** [comment] 2018-02-22 07:41
Hi @ittrend4710 

in order to clean up the database you need wait for 10.0.8 - we had to push out some hotfixes with 10.0.6 and 10.0.7.

But you can independently update the calendar app via the market app in our owncloud.
Or download the app on the marketplace https://marketplace.owncloud.com/apps/calendar

**Comment by sjlongland** [comment] 2018-03-15 07:49
I just had the same issue with the calendar in ownCloud 10.0.7, we have a shared calendar that's owned by the administrator user, which all members are able to edit… except:

1. in my migration from OwnCloud 6 to 10, it had made the calendar read-only to all but the administrator.  (Easy fix, just tick a box.)
2. the aforementioned bug still prevented me, as a regular user, from adding to that calendar.

Updating the calendar module fixed the latter issue, and now, as a regular user, I can create and edit events.

**Comment by DeepDiver1975** [comment] 2018-03-15 12:37
looks like everything is fixed now -> close

**Closed as completed by DeepDiver1975** 2018-03-15 12:37 UTC
