### ISSUE TITLE
Undefined month in catalan language

### ISSUE THREAD

**Issue by IzK666** [owncloud/calendar#820] opened 2017-10-01 12:21 UTC
In version 1.5.4 instead of "Octubre 2017" there is an "Undefined 2017". In earlier version, v1.4.1, worked fine.
The calendar and the appointments are correct. The error is just that I have to count how many times I go forth or back to know which month is displayed.
I have tried other languages (spanish, english and français) and there is no error.

I'm using OC9.1.6.

The logs sais that "/apps/calendar/js/vendor/autosize/dist/autosize.js" is missing.

**Comment by DeepDiver1975** [comment] 2017-10-02 13:00
> The logs sais that "/apps/calendar/js/vendor/autosize/dist/autosize.js" is missing.

similar to #821

**Comment by DeepDiver1975** [comment] 2017-10-02 13:01
> In version 1.5.4 instead of "Octubre 2017" there is an "Undefined 2017". In earlier version, v1.4.1, worked fine.

looks like some translation is missing .....

**Comment by DeepDiver1975** [comment] 2017-10-02 13:04
> looks like some translation is missing .....

confirmed - afaik these translations come from moment.js ...

**Comment by IzK666** [comment] 2017-10-02 19:12
DeepDiver, which file is "moment.js". I can't find it in OC anywhere.
If you tell me where are the strings, I can translate them on transifex.

On the other side, I don't think it's a translation problem, as any untranslated string appears in english.

**Comment by DeepDiver1975** [comment] 2017-10-02 20:08
> DeepDiver, which file is "moment.js". I can't find it in OC anywhere.
> If you tell me where are the strings, I can translate them on transifex.

this one - https://github.com/owncloud/core/blob/v9.1.6/core/vendor/moment/min/moment-with-locales.js

I'll have a closer look ....

**Comment by Julian1998** [comment] 2018-03-19 13:48
Duplicate of https://github.com/owncloud/calendar/issues/814

**Closed as completed by Julian1998** 2018-03-19 13:48 UTC
Labels: bug
