### ISSUE TITLE
Cannot create event in Calendar app

### ISSUE THREAD

**Issue by lwinch2006** [owncloud/calendar#719] opened 2016-08-27 12:39 UTC
### Steps to reproduce
1. Navigate to owncloud URL.
2. Choose Calendar app from the menu
3. Double click with the mouse on some date to try to create new event.
### Expected behaviour

Form for creation of new event should appear.
### Actual behaviour

Nothing happens.
### Server configuration

Debian GNU/Linux 8.5 (jessie)

**Web server:**
Apache/2.4.10 (Debian)

**Database:**
mysql  Ver 14.14 Distrib 5.5.50, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 08:17:07) 

**Server version:** (see your admin page)
ownCloud 9.1.0 (stable)

**Calendar version:** (see the apps page)
 Calendar 1.3.3

**Updated from an older installed version or fresh install:**
Fresh installation from apps.owncloud.com (Updating of old versions is also tried)

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - bookmarks: 0.8.1
  - calendar: 1.3.3
  - comments: 0.3.0
  - contacts: 1.3.1.0
  - dav: 0.2.5
  - documents: 0.13.1
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notes: 2.0.2
  - notifications: 0.3.0
  - ownnote: 1.08
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.3
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - galleryplus
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => [some id here],
  'passwordsalt' => [some password salt here],
  'secret' => [some secret here],
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => [some ip address here],
    2 => [some another ip address here],
    3 => [some DNS name here],
  ),
  'datadirectory' => [some data directory here separated from owncloud root folder],
  'overwrite.cli.url' => 'https://[some ip:port here]/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => [some db user here],
  'dbpassword' => [some db password here],
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'loglevel' => 3,
  'maintenance' => false,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration

**Browser:**
Firefox Developer Edition 50.0a2
Firefox 48.0.2
Mozilla Iceweasel 38.5.0

**Operating system:**
Archlinux x86_64 Linux 4.7.2-1-ARCH

**CalDAV-clients:**
Web version of Calendar app
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
JQMIGRATE: Migrate is installed, version 1.4.0      jquery-migrate.min.js:2:542

TypeError: component is null    [Learn More]                     ical.js:2498:1

Component.prototype.addSubcomponent                         ../owncloud/apps/calendar/js/vendor/ical.js/build/ical.js:2498:1
date                                                        ../owncloud/apps/calendar/js/public/app.js:3175:6
patch                                                       ../owncloud/apps/calendar/js/public/app.js:3287:5
VEvent.fromStartEnd                                         ../owncloud/apps/calendar/js/public/app.js:3655:3
select                                                      ../owncloud/apps/calendar/js/public/app.js:235:17
trigger                                                     ../owncloud/apps/calendar/js/vendor/fullcalendar/dist/fullcalendar.js:10114:11
FC.View<.trigger                                            ../owncloud/apps/calendar/js/vendor/fullcalendar/dist/fullcalendar.js:7931:10
FC.View<.triggerSelect                                      ../owncloud/apps/calendar/js/vendor/fullcalendar/dist/fullcalendar.js:8742:3
FC.View<.reportSelection                                    ../owncloud/apps/calendar/js/vendor/fullcalendar/dist/fullcalendar.js:8736:3
FC.Grid<.buildDayDragListener/dragListener<.interactionEnd  ../owncloud/apps/calendar/js/vendor/fullcalendar/dist/fullcalendar.js:3732:7
FC.DragListener<.trigger                                    ../owncloud/apps/calendar/js/vendor/fullcalendar/dist/fullcalendar.js:2785:4
FC.DragListener<.handleInteractionEnd                       ../owncloud/apps/calendar/js/vendor/fullcalendar/dist/fullcalendar.js:2552:3
HitDragListener<.handleInteractionEnd                       ../owncloud/apps/calendar/js/vendor/fullcalendar/dist/fullcalendar.js:3135:3
FC.DragListener<.endInteraction                             ../owncloud/apps/calendar/js/vendor/fullcalendar/dist/fullcalendar.js:2539:4
.proxy/f                                                    ../owncloud/core/vendor/jquery/dist/jquery.min.js:2:3726
n.event.dispatch                                            ../owncloud/core/vendor/jquery/dist/jquery.min.js:3:6414
n.event.add/r.handle                                        ../owncloud/core/vendor/jquery/dist/jquery.min.js:3:3224




```

**Comment by georgehrke** [comment] 2016-08-29 10:23
Can you please provide the config.php? 
(You can obviously mask private information :))

**Comment by georgehrke** [comment] 2016-08-29 10:24
Do you use the asset pipeline feature?

**Comment by lwinch2006** [comment] 2016-09-04 11:55
- Hi. I updated issue description and added config. Hope this helps. 
- And I suppose I don't use any asset pipeline feature since have not enabled it in my config as I searched the Google this key `asset-pipeline.enabled` should be in `config.php`.

**Comment by lwinch2006** [comment] 2016-09-04 12:00
- Also I can mention that this Javascript exception is raised each time man double clicks on some date in the Calendar UI (as you can see on the attached picture).

![003](https://cloud.githubusercontent.com/assets/6912915/18230842/0df94616-7297-11e6-80a2-1980e7427456.jpg)

**Comment by georgehrke** [comment] 2016-09-04 12:01
have you tried clicking just once?

**Comment by lwinch2006** [comment] 2016-09-04 12:04
- I tried now. Actually this js exception raises on each click and I suppose it is raised twice on double click.

**Comment by lwinch2006** [comment] 2016-09-04 12:08
- Some more info. If I click on events that already exists in Calendar like birthdays so "event info/edit dialog" appears as it should, no exceptions. They happen just when I try to create new event.

**Comment by nhoening** [comment] 2016-09-04 19:32
I also struggle with this behaviour, but I don't see any error in the console (happens in Chrome and IE for me), in the beginning also in FF but it works there now.
Edit: Sorry, update to 1.3.3 fixed it.

**Comment by martingabelmann** [comment] 2016-09-05 10:35
Same issue here for quite a long time in Qutebrowser (i can remember that it worked there for some time but since they are doing a lot of changes in their backend i waited for a request).  
Now I also get the TypeError in Firefox 48.0.2 and Chromium 52.0.2743.11 on Archlinux (calendar 1.3.3):

```
12:24:05.939 TypeError: component is null
Component.prototype.addSubcomponent()ical.js:2498
date()app.js:3175
patch()app.js:3287
VEvent.fromStartEnd()app.js:3655
select()app.js:235
trigger()fullcalendar.js:10114
FC.View<.trigger()fullcalendar.js:7931
FC.View<.triggerSelect()fullcalendar.js:8742
FC.View<.reportSelection()fullcalendar.js:8736
FC.Grid<.buildDayDragListener/dragListener<.interactionEnd()fullcalendar.js:3732
FC.DragListener<.trigger()fullcalendar.js:2785
FC.DragListener<.handleInteractionEnd()fullcalendar.js:2552
HitDragListener<.handleInteractionEnd()fullcalendar.js:3135
FC.DragListener<.endInteraction()fullcalendar.js:2539
.proxy/f()jquery.min.js:2
n.event.dispatch()jquery.min.js:3
n.event.add/r.handle()jquery.min.js:3
1ical.js:2498:1
```

last time i used windows (~5days) with firefox it worked.

**Comment by georgehrke** [comment] 2016-09-05 10:37
Did you install the calendar app from the app store or via the arch package?

**Comment by georgehrke** [comment] 2016-09-05 10:38
I'm not able to reproduce this issue and the thing you all have in common is using arch.

**Comment by georgehrke** [comment] 2016-09-05 10:38
I'm assuming some issue in the arch package of the calendar

**Comment by martingabelmann** [comment] 2016-09-05 10:41
Sorry if i wasnt clear enough: my client is on archlinux.  
The server is on Alpine installed with the webinstaller.

edit: calendar app is installed via app store

**Comment by martingabelmann** [comment] 2016-09-05 10:51
Also: @lwinch2006 is using debian on the server side and  arch on the client side. So, it seems to be a client thingy?

**Comment by georgehrke** [comment] 2016-09-05 11:00
Ah, I think I have a clue.
Can you please open the javascript developer console, type `jstz.determine().name();` and post the output.

**Comment by martingabelmann** [comment] 2016-09-05 11:07
output is `Etc/UTC`.

btw. i recognized that the event times have a shift of -2 hours to my system time but the red line in the calendar is sync with my system time.

**Comment by georgehrke** [comment] 2016-09-05 11:09
> output is `Etc/UTC`.

I kind of expected that answer 🙈

> btw. i recognized that the event times have a shift of -2 hours to my system time but the red line in the calendar is sync with my system time.

Well, if all your events are in Europe/Berlin, that's the correct behavior.
I honestly never get why people set their desktops timezone to UTC 🙊

**Comment by martingabelmann** [comment] 2016-09-05 11:42
Argh :sob:  
Setting the system time to Europe/Berline fixed it for me :clap:  
(btw. UTC is Archs system default and i think also on Ubuntu if you used the alternate installation)

**Comment by martingabelmann** [comment] 2016-09-05 11:44
for clearness: it fixed both, the timeshift (of course) and the _create event_ issue

**Comment by georgehrke** [comment] 2016-09-05 11:51
Good :)

But anyway, there might be a legitimate use case for using UTC as your systems timezone (on a desktop), so this should definitely be fixed

**Comment by georgehrke** [comment] 2016-09-05 11:54
duplicate of https://github.com/owncloud/calendar/issues/666

i know that issue 666 already includes opening the events editor, but it comes down to the same issue.

**Closed as completed by georgehrke** 2016-09-05 11:54 UTC
Labels: 1 - to develop, bug
